### ISSUE TITLE
KMO based Matcher

### ISSUE THREAD

**Issue by ls-ash** [dk-liang/CLTR#5]
After reading your article and code, I am interested in the part of Matcher, but I do not find KMO based Matcher in the code. Is it in the module or something else?

**Comment by ds2268** [comment]
Yes, I can also only see the basic L1 implementation of the matcher.

**Comment by ds2268** [comment]
@dk-liang: Can you also provide a KMO-based mather in order to reproduce the results in new publications?

**Comment by ryan-seungyong-lee** [comment]
@ds2268 Did you get KMO-based matcher? I can't find it in this repository...

**Comment by congyi-lcy** [comment]
I met the same problem. Did you solve it?





> Yes, I can also only see the basic L1 implementation of the matcher.

**Comment by ryan-seungyong-lee** [comment]
> I met the same problem. Did you solve it?
> 
> > Yes, I can also only see the basic L1 implementation of the matcher.

No.. not yet 🤣

**Comment by congyi-lcy** [comment]
All right... That is，it feels like this paper just moved DETR to the crowd counting task，without any other greater improvements😵‍💫
---- Replied Message ----
| From | ***@***.***> |
| Date | 07/10/2023 22:41 |
| To | dk-liang/CLTR ***@***.***> |
| Cc | ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [dk-liang/CLTR] KMO based Matcher (Issue #5) |

I met the same problem. Did you solve it?

Yes, I can also only see the basic L1 implementation of the matcher.

No.. not yet 🤣

**Comment by ryan-seungyong-lee** [comment]
> All right... That is，it feels like this paper just moved DETR to the crowd counting task，without any other greater improvements😵‍💫 ---- Replied Message ---- | From | ***@***.***> | | Date | 07/10/2023 22:41 | | To | dk-liang/CLTR ***@***.***> | | Cc | ***@***.***>, Comment ***@***.***> | | Subject | Re: [dk-liang/CLTR] KMO based Matcher (Issue #5) | I met the same problem. Did you solve it? Yes, I can also only see the basic L1 implementation of the matcher. No.. not yet 🤣 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

I agree, this paper only use conditional DETR without bounding boxes and class information. I think a main novelty is the KMO matcher, but they didn't open this as a open source :(

**Comment by congyi-lcy** [comment]
Well. thank you for replying and communicating together
---- Replied Message ----
| From | ***@***.***> |
| Date | 07/10/2023 22:53 |
| To | dk-liang/CLTR ***@***.***> |
| Cc | ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [dk-liang/CLTR] KMO based Matcher (Issue #5) |

All right... That is，it feels like this paper just moved DETR to the crowd counting task，without any other greater improvements😵‍💫 ---- Replied Message ---- | From | @.> | | Date | 07/10/2023 22:41 | | To | dk-liang/CLTR @.> | | Cc | @.>, Comment @.> | | Subject | Re: [dk-liang/CLTR] KMO based Matcher (Issue #5) | I met the same problem. Did you solve it? Yes, I can also only see the basic L1 implementation of the matcher. No.. not yet 🤣 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>

I agree, this paper only use conditional DETR without bounding boxes and class information. I think a main novelty is the KMO matcher, but they didn't open this as a open source :(
